// <auto-generated />
using System;
using DelivAssist.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DelivAssist.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250617051803_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.6");

            modelBuilder.Entity("DelivAssist.Models.Delivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("App")
                        .HasColumnType("INTEGER");

                    b.Property<double>("BasePay")
                        .HasColumnType("REAL");

                    b.Property<string>("CustomerNeighborhood")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DeliveryTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Restaurant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RestaurantStreetAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("TipPay")
                        .HasColumnType("REAL");

                    b.Property<double>("TotalPay")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("DelivAssist.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DelivAssist.Models.UserDelivery", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateAdded")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "DeliveryId");

                    b.HasIndex("DeliveryId");

                    b.ToTable("UserDeliveries");
                });

            modelBuilder.Entity("DelivAssist.Models.UserDelivery", b =>
                {
                    b.HasOne("DelivAssist.Models.Delivery", "Delivery")
                        .WithMany("UserDeliveries")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DelivAssist.Models.User", "User")
                        .WithMany("UserDeliveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DelivAssist.Models.Delivery", b =>
                {
                    b.Navigation("UserDeliveries");
                });

            modelBuilder.Entity("DelivAssist.Models.User", b =>
                {
                    b.Navigation("UserDeliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
