name: Run Backend Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore ./GigBoardBackend/GigBoardBackend.csproj

      - name: Build
        run: dotnet build ./GigBoardBackend/GigBoardBackend.csproj --no-restore

      - name: Run tests and generate report
        run: dotnet test GigBoard.Tests/GigBoard.Tests.csproj --logger "console;verbosity=detailed"