name: Run Backend Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests and generate report
        run: dotnet test DelivAssist.Tests/DelivAssist.Tests.csproj --logger "console;verbosity=detailed" --logger "trx;LogFileName=test_results.trx" --results-directory ./TestResults

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./TestResults

      - name: Publish test results
        uses: dorny/test-reporter@v1
        if: alwys()
        with:
          name: .NET Test Results
          path: ./TestResults/test_results.trx
          reporter: dotnet-trx
          fail-on-error: false